# SPDX-FileCopyrightText: 2025 Name <lasagna@garfunkle.space>
#
# SPDX-License-Identifier: CC-BY-SA-4.0

## This file is for REUSE compliance. Refer to https://reuse.software/tutorial/ for more information.
version = 1

# Applies CC-BY-SA-4.0 to all textual files
[[annotations]]
path = [
    "*.webp",
    ".git*",
    ".envrc"
]
SPDX-FileCopyrightText = "2024 Name <lasagna@garfunkles.space>"
SPDX-License-Identifier = "CC-BY-SA-4.0"

# Applies EUPL-1.2 to flake.nix
[[annotations]]
path = "flake.lock"
SPDX-FileCopyrightText = "2024 Name <lasagna@garfunkles.space>"
SPDX-License-Identifier = "EUPL-1.2"
